apiVersion: v1alpha1
generated: "2018-06-13T09:24:07.392654524Z"
kind: RepositoryContent
services:
  - apiVersion: v1alpha1
    kind: ServiceTemplate
    metadata:
      name: golang-template
      platforms:
        - linux
    spec:
      description: Golang Application with GoReleaser
      icon: https://raw.githubusercontent.com/metcalfc/golang-template/master/img/golang.png
      source:
        image: metcalfc/golang-template
      title: Golang Application with GoReleaser
      parameters:
        - name: username
          description: GitHub Username
          type: string
        - name: docker_username
          description: Docker Hub Username
          type: string
        - name: accessToken
          description: GitHub Access token
          type: string
        - name: repoName
          description: GitHub / Docker Hub Repository name
          type: string
