FROM golang:1.13 as builder

# Create a non root user.
RUN adduser --disabled-password --disabled-login --gecos "" user

COPY /{{PROJECT}} /

ENTRYPOINT ["/{{PROJECT}}"]

FROM scratch

# Import the user and group files from the builder.
COPY --from=builder /etc/passwd /etc/passwd
# Copy our static executable.
COPY --from=builder /{{PROJECT}} /
# Use an unprivileged user.
USER user

ENTRYPOINT ["/{{PROJECT}}"]
